version: 1.0.0
server:
  port: 8100
spring:
  application:
    name: origin-admin-001
  profiles:
    active: druid

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.origin.admin.entity.po

# mybatis分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

logging:
  level:
    com.origin.admin.mapper: debug

captcha:
    enable: false

swagger:
    autoOpenEnable: true
    title: Origin接口文档
    description: Spring Boot 利用Swagger2构建Api文档
    version: 1.0.0

key-bits: 8
