version: 1.0.0
server:
  port: 8100
spring:
  application:
    name: origin-admin-001
  profiles:
    active: druid
  redis:
    database: 0
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-idle: 10 # 连接池中的最大空闲连接
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.origin.admin.entity.po # 注意：对应实体类的路径
# mybatis分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

logging:
  level:
    com.origin.admin.mapper.*: debug

captcha:
    enable: false
swagger:
    autoOpenEnable: true
